name: Get Running Workflows
description: Get existing workflows which are in progress or queued
inputs:
  GITHUB_TOKEN:
    required: true
    description: Token for auth
outputs:
  workflows_running:
    description: true if there are existing workflows
    value: something
runs:
  using: composite
  steps:
    - run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.TOKEN }}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
      shell: bash