name: Check Running Workflows
description: Check for existing workflows which are in progress or queued
inputs:
  token:
    required: true
    description: token for api call (secrets.GITHUB_TOKEN)
  SENDGRID_TOKEN:
    required: true
    description: Token used for sendgrid auth
  EMAIL_SENDER:
    required: true
    description: Email used to send mail
runs:
  using: composite
  steps:
    - name: Get Current workflow_id
      id: get_id
      run: |
        echo "Getting the current workflow_id..."
        curl -sL \
        --url https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" > workflow_run.json
        echo "workflow_id=$(jq -r '.workflow_id' workflow_run.json)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Get Queued Runs
      run: |
        echo "Getting the list of queued runs..."
        curl -sL \
        --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get_id.outputs.workflow_id }}/runs?status=queued \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" > queued_runs.json
        printf "Queued Runs:\n$(jq -r '.workflow_runs[].run_number' queued_runs.json | tee -a all_runs.txt)"
      shell: bash
    - name: Get In Progress Runs
      run: |
        echo "Getting the list of in progress runs..."
        curl -sL \
        --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get_id.outputs.workflow_id }}/runs?status=in_progress \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" > in_progress_runs.json
        printf "In Progress Runs:\n$(jq -r '.workflow_runs[].run_number' in_progress_runs.json | tee -a all_runs.txt)"
      shell: bash
    - name: Log All Runs
      run: |
        printf "All Runs:\n$(cat all_runs.txt)"
      shell: bash
    - name: Check Existing Runs
      id: check_existing
      env:
        CURRENT_RUN_NUMBER: ${{ github.run_number }}
      run: |
        chmod +x ${{ github.action_path }}/scripts/get_existing_runs.sh
        ${{ github.action_path }}/scripts/get_existing_runs.sh
      shell: bash
    - if: steps.check_existing.outputs.existing_runs != 'true'
      run: |
        echo "No existing runs found. Action will proceed."
      shell: bash
    - if: steps.check_existing.outputs.existing_runs == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          core.setFailed("Failing the action as the current run number is ${{ github.run_number }} \
          but we found a workflow running with run number ${{ steps.check_existing.outputs.existing_run_number }}.")
    - if: always()
      uses: actions/checkout@v3
    - if: always()
      uses: ./.github/actions/notify_pusher
      with:
          SENDGRID_TOKEN: ${{ inputs.SENDGRID_TOKEN }}
          EMAIL_SENDER: ${{ inputs.EMAIL_SENDER }}
