name: Notify Pusher
description: Send email to pusher if action fails
inputs:
  SENDGRID_TOKEN:
    required: true
    description: Token used for sendgrid auth
  EMAIL_SENDER:
    required: true
    description: Email used to send mail
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Notify pusher
      env:
        SENDGRID_TOKEN: ${{ inputs.SENDGRID_TOKEN }}
        EMAIL_SENDER: ${{ inputs.EMAIL_SENDER }}
        PUSHER_EMAIL: ${{ github.event.pusher.email }}
      run: python ${{ github.action_path }}/send_email.py
      shell: bash
    
