name: Check Running Workflows
description: Check for existing workflows which are in progress or queued
outputs:
  workflows_running:
    description: true if there are existing workflows
    value: ${{ steps.check_existing.outputs.existing_runs }}
runs:
  using: composite
  steps:
    - name: Install Jq Package
      run: sudo apt install jq
      shell: bash
    - name: Get Current workflow_id
      id: get_id
      run: |
        curl -L \
        --url https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" > workflow_run.json
        echo "workflow_id=$(jq -r '.workflow_id' workflow_run.json)" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Get Queued Runs
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get_id.outputs.workflow_id }}/runs?status=queued > queued_runs.json
        jq -r '.workflow_runs[].run_number' queued_runs.json >> all_runs.txt
      shell: bash
    - name: Get In Progress Runs
      run: |
        curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ steps.get_id.outputs.workflow_id }}/runs?status=in_progress > in_progress_runs.json
        jq -r '.workflow_runs[].run_number' in_progress_runs.json >> all_runs.txt
      shell: bash
    - name: Check Existing Runs
      id: check_existing
      env:
        CURRENT_RUN_NUMBER: ${{ github.run_number }}
      run: |
        chmod +x /get_existing_runs.sh
        /get_existing_runs.sh
      shell: bash       
