name: Serial Workflow
on: [push]

jobs:
  check_job:
    runs-on: ubuntu-latest
    name: Check Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Running Workflows
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # SENDGRID_TOKEN: ${{ secrets.SENDGRID_TOKEN }}
          # EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}