name: Serial Workflow
on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Main Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Check Running Workflows
        uses: ./.github/actions/check_running_workflows
      - name: Sleep # MAIN STEP HERE
        if: success()
        run: sleep 30s
        shell: bash
      # - name: Notify pusher
      #   if: failure() # if: failure()
      #   uses: ./.github/actions/notify_pusher
      #   with:
      #     SENDGRID_TOKEN: ${{ secrets.SENDGRID_TOKEN }}
      #     EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}